---
- name: Playbook to execute ping role
  hosts: rhel-db-servers
  vars_files:
     - vars.yml
  roles:
     - os-disk-partition-resize
     - mq-file-system-mount
     - jump-file-system-mount
     - user-group
     - reboot
