---
- name: Playbook to execute file sytem mount and user group creation
  hosts: rhel-mq-servers
  vars_files:
     - vars.yml
  roles:
     - os-disk-partition-resize
     - mq-file-system-mount
     - additional-disk-partition-file-system-mount
     - jump-file-system-mount
     - user-group
     - reboot
