---

# tasks file for logical volume creation , directory creation, file system format and file mount
- name: Check if marker for successful file system mount for jump server
  shell: "grep -i 'successful file system mount for jump' /tmp/fs_status.txt"
  register: jump_filesystem_mount_check
  become: yes
  ignore_errors: yes

- block:
    - name: Check if logical volumes exist
      shell: "lvs --noheadings | awk '{ print $1 }' | grep '{{item.lv}}'"
      loop: "{{ jump_specs }}"
      register: lv_check
      changed_when: false
      ignore_errors: yes

    - name: Create logical volumes
      lvol:
        vg: "{{ os_disk_volume_group }}"
        lv: "{{ item.lv }}"
        size: "{{ item.size }}"
      loop: "{{ jump_specs }}"
      when: lv_check is failed
    - name: Format logical volumes
      filesystem:
        fstype: xfs
        dev: "/dev/{{os_disk_volume_group}}/{{item.lv}}"
      loop: "{{ jump_specs }}"

    - name: Check if directories exist
      stat:
        path: "{{ item.path }}"
      register: existing_dirs
      loop: "{{ jump_specs }}"

    - name: Create directories if not present
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ jump_specs }}"
      when: not (item.path in existing_dirs.results | map(attribute='item.path') | list)

    - name: Mount the directories if not mounted
      mount:
        path: "{{ item.path }}"
        src: "/dev/mapper/{{os_disk_volume_group}}-{{ item.lv}}"
        fstype: xfs
        state: mounted
      loop: "{{ jump_specs }}"
    
    - name: Check if logical volume needs extending
      shell: "lvdisplay --units g /dev/rootvg/{{ item.lvpath }} | grep 'LV Size' | awk '{ print $3 }'"
      register: lv_size
      failed_when: lv_size.rc != 0
      loop: "{{ lv_extension_threshold }}"

    - name: Debug lv_size
      debug:
         var: lv_size

    - block:
        - name: Extend logical volume if free space is less than {{ item.resize }}G
          debug:
            msg: "Extending logical volume by {{ item.resize }}G"
          loop: "{{ lv_extension_threshold }}"
          loop_control:
            index_var: item_index

        - name: Extend logical volume if free space is less than threshold {{ item.resize }} G
          lvol:
            vg: rootvg
            lv: "{{ item.lvpath }}"
            size: "{{ item.resize }}G"
          register: lv_extend
          loop: "{{ lv_extension_threshold }}"
          loop_control:
            index_var: item_index

    - name: Add marker to indicate successful file system mount for jump server
      lineinfile:
        path: /tmp/fs_status.txt
        line: "successful file system mount for jump"
        create: yes
  become: yes
  when: jump_filesystem_mount_check is changed and jump_filesystem_mount_check.rc != 0

